name: Release album2vid

on:
  push:
    branches: ["main"]

permissions:
  contents: write
  # packages: write
  # issues: write
  # id-token: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Get tag
        id: gen-tag
        run: |
          version=$(cat version.json | jq -r .version)
          echo tag="v$version" >> $GITHUB_OUTPUT
      - name: Push tag to repo
        uses: actions/github-script@v9
        with:
          script: |
            try {
              github.rest.git.createRef({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: 'refs/tags/${{steps.gen-tag.outputs.tag}}',
                sha: context.sha
              })
            } catch (error) {
              console.log('Tag already exists, skipping tag creation.')
            }
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: "1.26.2"
      # More assembly might be required: Docker logins, GPG, etc.
      # It all depends on your needs.
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v7
        with:
          # either 'goreleaser' (default) or 'goreleaser-pro'
          distribution: goreleaser
          # 'latest', 'nightly', or a semver
          version: "~> v2"
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Your GoReleaser Pro key, if you are using the 'goreleaser-pro' distribution
          # GORELEASER_KEY: ${{ secrets.GORELEASER_KEY }}
